#                                              #
# Starship Config by a3chron, catppuccin theme #
#                                              #

palette = "catppuccin_mocha"

format = """
[╭─](overlay0)$sudo$username$hostname$localip$directory$read_only$git_branch$git_metrics ${env_var.hermit}[$fill $cmd_duration ┘](overlay0)
[╰─ $battery $character](overlay0) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
command_timeout = 500
add_newline = true

# Catppuchin Theme

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[username]
style_user = 'teal bold'
format = ' [$user@]($style)'
disabled = false
show_always = true

[sudo]
format = ' [sudo](bold red)'
disabled = false

[ocaml]
format = '[Ocaml](bold pink) [$version](bold dimmed pink) '

[localip]
ssh_only = false
format = '[@$localipv4](bold dimmed blue) '
disabled = false

[hostname]
ssh_only = false
ssh_symbol = 'ssh:'
format = '[$ssh_symbol](bold dimmed maroon)[$hostname](bold dimmed sapphire)'
trim_at = ''
disabled = false

[git_metrics]
disabled = false
format = ' [+$added](bold teal)[-$deleted](bold pink)'

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = 'bold pink'

[fill]
symbol = ' '
style = 'bold base'

# time of command
[cmd_duration]
min_time = 500
format = ' [$duration](bold dimmed flamingo)'

# hermit environment indicator
[env_var.hermit]
variable = 'HERMIT_ENV'
symbol = '🐚'
format = '[$symbol]($style)'
style = 'bold teal'

[directory]
fish_style_pwd_dir_length = 5
disabled = false
truncation_length = 5
truncation_symbol = '…/'
read_only = ' read-only'
read_only_style = 'bold dimmed mauve'
style = 'bold mauve'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# battery
[battery]

full_symbol = '● '
charging_symbol = '◉ '
discharging_symbol = '◯ '

[[battery.display]]
threshold = 20
style = 'red'

[[battery.display]]
threshold = 100
style = 'teal'

[character]
success_symbol = '[──╌╌](overlay0)'
error_symbol = '[──╌╌](red)'

