require('plugins.mini')
require('plugins.colorscheme')
require('plugins.lsp')
require('plugins.oil')
require('plugins.flash')
require('plugins.haunt')
require('plugins.highlight-colors')
require('plugins.conform')
