require('plugins.colorscheme')
require('plugins.lsp')
require('plugins.oil')
require('plugins.fzf')
require('plugins.flash')
require('plugins.haunt')
require('plugins.surround')
require('plugins.nvim-kitty')
