os:
  editPreset: 'nvim'

git:
  pagers:
    - pager: delta --dark --paging=never --side-by-side --features collared-trogon

gui:
  # Show flat file list by default
  showFileTree: false

  # Hide command log by default
  showCommandLog: false

  # Use nerdfonts
  nerdFontsVersion: "3"

  authorColors:
    # use highlight color for self
    'Fabian Junkert': '#f9e2af'
    # use color-x for all others
    '*': '#89b4fa'

  # Use the mocha catppuccin theme
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
